version: "3.9"

services:
  api-bun:
    image: "api-bun"
    build:
      context: ./
      dockerfile: Dockerfile
      target: release
    init: true
    ports:
      - "4400:4400"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - ARGON_MEMORY_COST=${ARGON_MEMORY_COST}
      - ARGON_TIME_COST=${ARGON_TIME_COST}
      - ARGON_PARALLELISM=${ARGON_PARALLELISM}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_AT=${JWT_EXPIRES_AT}
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - BREVO_API_KEY=${BREVO_API_KEY}

    restart: unless-stopped

  db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33036:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql -u root -p$${MYSQL_ROOT_PASSWORD} -e 'USE ${MYSQL_DATABASE};' || exit 1",
        ]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 30s
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:8.4.0
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command:
      - sh
      - -c
      - |
        redis-server --requirepass "$REDIS_PASSWORD"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  mysql-data:
